### ISSUE TITLE
Concurency

### ISSUE THREAD

**Issue by kofifus** [ababik/Remute#12] opened 2019-02-08 03:42 UTC
Shouldn't the dictionaries in https://github.com/ababik/Remute/blob/master/Remute/Remute.cs#L28-L29

be protected with a lock ?

Thanks!

**Comment by ababik** [comment] 2019-02-08 05:58
I don't think `lock` or `ConcurrentDictionary` is required here.
I use `TryGetValue` and then write item using indexer. In the worst case item will be written multiple times at the beginning. I think synchronization expenses are worst than possible repeated operation once.

**Comment by kofifus** [comment] 2019-02-08 06:38
You're probably right :)

**Comment by IanYates** [comment] 2019-02-10 03:39
@ababik - fair thinking.  And, as you say, if the same effective value is written multiple times then it's not a big deal.

However...  Please consider https://stackoverflow.com/a/3439721/1053381
The issue is that the write *may* be mutating the dictionary's internal state - eg doing an internal array resize to accommodate the extra key/value - and that could upset
- other parallel writers (often what concerns people)
- a reader reading from the dictionary at the same time  (often overlooked)

A ConcurrentDictionary will avoid these scenarios.  It still has very minimal locking overhead and, in the least effort approach where you just change the types, you'll still have the property where multiple calculations of what's effectively the same value will have a 'last writer wins'   (the way around that, if the calculation is expensive, is to use Lazy inside of the dictionary so only a yet-to-be-evaluated Lazy is potentially made multiple times)

**Comment by kofifus** [comment] 2019-02-10 09:12
(my preference would be ImmutableDictionary)

**Comment by IanYates** [comment] 2019-02-10 10:04
Another reference: MSDN blog post (I knew I'd read something more definitive about this previously)

https://blogs.msdn.microsoft.com/tess/2009/12/21/high-cpu-in-net-app-using-a-static-generic-dictionary/

ImmutableDictionary would be fine too.  Extra dependency, but probably not a big deal.

**Comment by ababik** [comment] 2019-02-11 23:55
Thanks everybody for the information. I agree I'll change it to be `ConcurrentDictionary`.

**Comment by ababik** [comment] 2019-02-12 05:56
Fixed by using `ConcurrentDictionary`.

**Closed by ababik** 2019-02-12 05:56 UTC
